AWS_BUCKET_NAME="file-info"
AWS_ACCESS_KEY=''
AWS_SECRET_ACCESS_KEY=''
AWS_ACCESS_KEY="AKIA6HKHMU3HNZCX5RML"
AWS_SECRET_ACCESS_KEY="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"
AWS_DOMAIN= 'http://lab3example.s3.amazonaws.com/'
AWS_REGION="us-east-1"